### ISSUE TITLE
Add .sandstorm/.vagrant/ to .sandstorm/.gitignore

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/vagrant-spk#54] opened 2015-08-06 16:29 UTC
Otherwise people end up commiting their VirtualBox state, which is not something that should live in version control.

**Comment by zarvox** [comment] 2015-08-06 20:02
Duplicate of #30 .

**Comment by paulproteus** [comment] 2015-08-06 20:02
Thanks.

**Closed by zarvox** 2015-08-06 20:02 UTC
